apiVersion: apps/v1
kind: Deployment
metadata:
  name: lucas-calculator-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lucas-calculator-frontend
  template:
    metadata:
      labels:
        app: lucas-calculator-frontend
    spec:
      containers:
      - name: frontend
        image: harbor.kakor.ovh/ipim2il/lucas-calculator-frontend:latest
        ports:
        - containerPort: 5173
        env:
        - name: VITE_API_URL
          value: "http://lucas-calculator-backend:3000"

---

apiVersion: v1
kind: Service
metadata:
  name: lucas-calculator-frontend
spec:
  selector:
    app: lucas-calculator-frontend
  ports:
  - name: http
    port: 5173
    targetPort: 5173

---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: lucas-calculator-frontend
spec:
  to:
    kind: Service
    name: lucas-calculator-frontend
  port:
    targetPort: 5173