apiVersion: v1
kind: PersistentVolume
metadata:
  name: lucas-mongo-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  nfs:
    path: /Volume1/public/nfs-share-openshift/groupe-1
    server: 192.168.1.56

---

apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: lucas-mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: slow

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: lucas-calculator-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lucas-calculator-mongo
  template:
    metadata:
      labels:
        app: lucas-calculator-mongo
    spec:
      containers:
      - name: lucas-calculator-mongo
        image: mongo:7.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "password"
        - name: MONGO_INITDB_DATABASE
          value: "calculator"
        volumeMounts:
        - name: lucas-mongo-storage
          mountPath: /data/db
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: lucas-mongo-storage
        persistentVolumeClaim:
          claimName: lucas-mongo-pvc
      - name: init-script
        configMap:
          name: lucas-mongo-init-config

---

apiVersion: v1
kind: Service
metadata:
  name: lucas-calculator-mongo
spec:
  selector:
    app: lucas-calculator-mongo
  ports:
  - port: 27017
    targetPort: 27017

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: lucas-mongo-init-config
data:
  init-mongo.js: |
    db.createUser({
      user: 'admin',
      pwd: 'password',
      roles: [
        {
          role: 'readWrite',
          db: 'calculator'
        },
        {
          role: 'dbAdmin',
          db: 'calculator'
        }
      ]
    });

    db = db.getSiblingDB('admin');

    db.createUser({
      user: 'admin',
      pwd: 'password',
      roles: ['userAdminAnyDatabase', 'readWriteAnyDatabase']
    }); 