apiVersion: v1
kind: Secret
metadata:
  name: lucas-calculator-secrets
type: Opaque
data:
  jwt-secret: Y2FsY3VsYXRyaWNlLWp3dC1zZWNyZXQtMjAyNg==
  mongo-username: Y2FsY3VsYXRvcl91c2Vy
  mongo-password: U2VjdXJlUGFzczIwMjYh